
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gajceuvnerzlnuqvhnan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhamNldXZuZXJ6bG51cXZobmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzM1MzgsImV4cCI6MjA2MTUwOTUzOH0.7gsaxDRXCGBALLfbAawQoFZEPxATam_0oWdgig5oDIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});

